server:
  listen: 3000
  workers: 2
  upstreams:
    - id: "node1"
      url: "jsonplaceholder.typicode.com"
    - id: "node2"
      url: "localhost:8081"
  headers:  
    - key: "X-Forwarded-For"
      value: "$ip"
    - key: Authorization
      value: 'Bearer xyz'
  rules:
    - path: "/api"
      upstreams: ["node1", "node2"]
    - path: "/admin"
      upstreams: ["node2"]
    - path: /todos
      upstreams: ["node1"]
