server:
  listen: 3000
  upstreams:
    - id: "node1"
      url: "jsonplaceholder.typicode.com"
    - id: "node2"
      url: "localhost:8081"
  headers:  
    - key: "X-Forwarded-For"
      value: "$ip"
    - key: Authorization
      value: 'Bearer xyz'
  rules:
    - path: /users
      upstreams: ["node1"]
    - path: /comments
      upstreams: ["node1"]
    - path: /todos
      upstreams: ["node1"]